name: test maherwertsteuer
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Post a message in a channel
            uses: slackapi/slack-github-action@v2.1.1
            with:
              webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
              webhook-type: incoming-webhook
              payload: |
                text: "Test. Pipeline ${{ github.workflow }} ist fertig"
              
          - name: node install
            uses: actions/setup-node@v4
            with:
                  node-version: "20"

          - name: npm install
            run: |
                  npm install

          - name: npm test
            run: |
                  npm test
          - name: npm coverage
            uses: actions/upload-artifact@v4
            with:
                  name: coverage-report
                  path: ./coverage
    deploy:
        needs: test
        if: ${{ success() }}
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v5

          - name: ssh setup
            run: |
              mkdir -p ~/.ssh
              echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/meinprivatekey
              chmod 600 ~/.ssh/meinprivatekey
              ssh-keyscan -H "${{secrets.EC2_IP}}" >> ~/.ssh/known_hosts

          - name: datei kopieren
            run: |
              scp -i ~/.ssh/meinprivatekey ./mehrwertsteuer.js ubuntu@${{secrets.EC2_IP}}:/home/ubuntu



          